name = "NestedEnvironments"
uuid = "cb6df31d-e3f2-4e74-89c5-02b08550c949"
authors = ["JinraeKim <kjl950403@gmail.com> and contributors"]
version = "0.2.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"

[compat]
julia = "1"
Transducers = "0.4"
DifferentialEquations = "6.16"
Parameters = "0.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
